### ISSUE TITLE
kmod-sched-fq_pie is missing from current master

### ISSUE THREAD

**Issue by chros73** [antoinedeschenes/openwrt-sqm#1]
Hi!

First of all, thanks for this repo!
I'm currently trying (compiling) to add cake support with it on OpenWRT 15.05.1.

I just noticed that the readme file says so, but the there's no `kmod-sched-fq_pie` package available.

```
Kernel Modules->Network Support->kmod-sched-fq_pie
```

**Comment by antoinedeschenes** [comment]
Hi @chros73, looks like I wasn't notified about your issue earlier... 

Thanks for notifying, I'll update the readme. I removed dependencies to `kmod-sched-fq_pie` in my repo since it's pretty much abandoned and doesn't compile in trunk builds anymore.

**Comment by chros73** [comment]
OK, cheers.
I managed to compile cake then, and I'm using it for 2 months now. Thanks!
